<div class="wrap">
<?php screen_icon(); ?>
    <h2>Infosys Collaboration</h2>
    <form method="post" action="options.php"> 
    <?php
        settings_fields('f51_infosys_options') ;?>

        <table class="form-table">
            <tr valign="top">
            <th scope="row">URL of Infosys installation</th>
            <td><input type="text" name="infosys-url" value="<?php echo get_option('infosys-url'); ?>" /></td>
            </tr>
             
            <tr valign="top">
            <th scope="row">Auth code for Infosys</th>
            <td><input type="text" name="authentication-code" value="<?php echo get_option('authentication-code'); ?>" /></td>
            </tr>
        </table>

        <?php submit_button(); ?>
    </form>
</div>
